apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
        
      restartPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key
      containers:
        - name: helloworld
          image: gcr.io/personal-342719/helloworld-msurmach:rc-<BUILD>
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /helloworld-ws/
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: helloworld
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
  - host: "maxsurm.me"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: helloworld-svc
            port:
              number: 8080
