apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      imagePullSecrets:
      - name: nexus
      containers:
        - name: helloworld
          image: 10.12.1.14:8085/helloworld-msurmach:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: prod
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

